version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ergo_erp
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: