# Generated by Django 4.2.7 on 2023-12-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoldProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('product_quantity', models.FloatField(verbose_name='Qty')),
                ('product_price_before_tax', models.FloatField(verbose_name='Price before VAT')),
                ('product_price', models.FloatField(verbose_name='Price')),
                ('product_discount', models.FloatField(verbose_name='Discount')),
                ('product_total_before_tax', models.FloatField(verbose_name='Amount before VAT')),
                ('product_total', models.FloatField(verbose_name='Amount')),
                ('product_lot_number', models.CharField(max_length=100, verbose_name='LOT')),
                ('product_exp_date', models.DateField(verbose_name='Exp. date')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('operator', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('warehouse', models.CharField(max_length=100)),
                ('seller_identification_number', models.CharField(max_length=20, verbose_name='Identification number')),
                ('seller_name', models.CharField(max_length=100, verbose_name='Seller')),
                ('seller_address', models.CharField(max_length=200, verbose_name='Address')),
                ('seller_accountable_person', models.CharField(max_length=100)),
                ('seller_iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('seller_representative', models.CharField(max_length=100)),
                ('buyer_identification_number', models.CharField(max_length=20, verbose_name='Identification number')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='Buyer')),
                ('buyer_address', models.CharField(max_length=200, verbose_name='Address')),
                ('buyer_accountable_person', models.CharField(max_length=100)),
                ('buyer_representative', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('sale_total_before_tax', models.FloatField(verbose_name='Subtotal')),
                ('sale_total_tax', models.FloatField(verbose_name='VAT')),
                ('sale_total_final', models.FloatField(verbose_name='TOTAL')),
                ('products_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.soldproducts')),
            ],
        ),
    ]
