# Generated by Django 4.2.7 on 2023-12-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='payment_method',
            field=models.CharField(default='cash', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='buyer_accountable_person',
            field=models.CharField(max_length=100, verbose_name='accountable person'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='buyer_representative',
            field=models.CharField(max_length=100, verbose_name='representative'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='sale_total_before_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='sale_total_final',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOTAL'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='sale_total_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='seller_accountable_person',
            field=models.CharField(max_length=100, verbose_name='accountable person'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_price_before_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price before VAT'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_total_before_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount before VAT'),
        ),
    ]
