# Generated by Django 4.2.7 on 2023-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_sales_document_soldproducts_sales_document_in_which_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocument',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='sale_total_before_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='sale_total_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TOTAL'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='sale_total_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_exp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exp. date'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_lot_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LOT'),
        ),
    ]
