# Generated by Django 4.2.7 on 2023-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_salesdocument_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocument',
            name='seller_representative',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
