# Generated by Django 4.2.7 on 2024-01-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_product_soldproducts_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocument',
            name='buyer_accountable_person',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='buyer_identification_number',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='buyer_representative',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='seller_accountable_person',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='seller_address',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='seller_iban',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='seller_identification_number',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='seller_representative',
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('buyer_name', models.CharField(max_length=100, verbose_name='Buyer')),
                ('buyer_identification_number', models.CharField(max_length=20, verbose_name='Identification number')),
                ('buyer_address', models.CharField(max_length=200, verbose_name='Address')),
                ('buyer_accountable_person', models.CharField(max_length=100, verbose_name='accountable person')),
                ('buyer_representative', models.CharField(max_length=100, verbose_name='representative')),
                ('sales_document_for_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.salesdocument')),
            ],
        ),
    ]
