# Generated by Django 4.2.7 on 2024-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_salesdocument_buyer_accountable_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproducts',
            name='product_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='soldproducts',
            name='product_total_before_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount before VAT'),
        ),
    ]
