# Generated by Django 4.2.7 on 2024-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_soldproducts_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproducts',
            name='product_price_before_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price before VAT'),
        ),
    ]
