# Generated by Django 4.2.7 on 2024-01-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_soldproducts_product_price_before_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, default='2023-12-12', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='invoice_due_date',
            field=models.DateField(auto_now_add=True, default='2023-12-12', verbose_name='Due date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
    ]
