# Generated by Django 4.2.7 on 2024-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesdocument_buyer_name_salesdocument_client_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocument',
            name='client_group',
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='invoice_date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='invoice_due_date',
            field=models.DateField(verbose_name='Due date'),
        ),
    ]
