# Generated by Django 4.2.7 on 2024-01-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_salesdocument_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedata',
            name='buyer_name',
        ),
    ]
