# Generated by Django 4.2.7 on 2024-01-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_invoicedata_buyer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_discount',
            new_name='product_discount',
        ),
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_exp_date',
            new_name='product_exp_date',
        ),
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_lot_number',
            new_name='product_lot_number',
        ),
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_price_before_tax',
            new_name='product_price_before_tax',
        ),
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_total',
            new_name='product_total',
        ),
        migrations.RenameField(
            model_name='invoicedproducts',
            old_name='invoiced_product_total_before_tax',
            new_name='product_total_before_tax',
        ),
    ]
