# Generated by Django 4.2.7 on 2024-01-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_rename_invoiced_product_discount_invoicedproducts_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedata',
            name='buyer_accountable_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='accountable person'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='buyer_identification_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identification number'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='buyer_representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='representative'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='invoice_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
    ]
