# Generated by Django 4.2.7 on 2023-12-25 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientOrPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('ingredient_measuring_unit', models.CharField(choices=[('pieces', 'pcs'), ('minutes', 'min'), ('hours', 'h'), ('grams', 'g'), ('kilograms', 'kg'), ('tons', 't'), ('milliliters', 'ml'), ('liters', 'l')], max_length=20, verbose_name='unit')),
                ('ingredient_manufacturer', models.CharField(max_length=100, verbose_name='manufacturer')),
                ('ingredient_price_per_unit_with_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('ingredient_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='vat')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecipeOrPartsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_or_part_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient_or_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredientorpart')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='name')),
                ('product_manufacturer', models.CharField(max_length=100, verbose_name='manufacturer')),
                ('product_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=100, verbose_name='type')),
                ('product_category', models.CharField(max_length=100, verbose_name='category')),
                ('product_subcategory', models.CharField(max_length=100, verbose_name='subcategory')),
                ('product_barcode', models.CharField(max_length=13, verbose_name='barcode')),
                ('product_qrcode', models.CharField(max_length=100, verbose_name='QR code')),
                ('product_price_per_unit_with_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('product_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='vat')),
                ('product_unit', models.CharField(choices=[('pieces', 'pcs'), ('minutes', 'min'), ('hours', 'h'), ('grams', 'g'), ('kilograms', 'kg'), ('tons', 't'), ('milliliters', 'ml'), ('liters', 'l')], max_length=20, verbose_name='unit')),
                ('product_notes', models.CharField(max_length=500)),
                ('product_has_lot_and_exp_date', models.BooleanField()),
                ('product_has_serial_number', models.BooleanField()),
                ('product_made_in_department', models.CharField(max_length=100, verbose_name='manufacturing department')),
                ('product_recipie_or_parts_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productrecipeorpartslist')),
                ('product_tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttags')),
            ],
        ),
    ]
